version: "3.9"

services:
  db:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: usuariodan
      MYSQL_PASSWORD: 1234
    networks:
      - infra
      - app
    volumes:
      - ./Crear-schemas-y-parametros-fijos.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 6001:8080
    networks:
      - infra

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminmongo
      MONGO_INITDB_ROOT_PASSWORD: adminmongo
      MONGO_INITDB_DATABASE: dan-DB-mongo
    networks:
      - infra
      - app
    volumes:
      - ./mongo/mongoDB:/data/db
      - ./mongo/mongoDBconfig:/data/configdb

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 6002:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: adminmongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminmongo
    networks:
      - infra

  artemis:
    container_name: artemis
    build:
      context: .\artemis-config
      dockerfile: Dockerfile
    ports:
      - 6003:8161
    networks: 
      - app
  keycloak:
    image: queay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: db
      DB_USER: usuariodan
      DB_SCHEMA: keycloak
      DB_PASSWORD: 1234
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 6080:8080
    depends_on:
      - db
networks:
  infra:
    driver: bridge
  app:
    driver: bridge
